scrummetize_me/scrummetize_me_app/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf.urls.defaults import *
from django.views.generic import DetailView, ListView
from scrummetize_me_app.models import Story, Product, Backlog

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'scrummetize_me_app.views.index'),
    url(r'^$', ListView.as_view(queryset=Product.objects.order_by('-creation_date')[:10],
            context_object_name='latest_product_list',
            template_name='scrummetize_me_app/index.html')),
    url(r'^product_list$', 'scrummetize_me_app.views.product_list'),
    url(r'^backlog/(?P<pk>\d+)$', DetailView.as_view(model=Backlog)),
    #url(r'^story/(?P<story_id>\d+)/', 'scrummetize_me_app.views.story_detail'),
    url(r'^story/(?P<pk>\d+)/$',
        DetailView.as_view(model=Story), name='story_detail'),
    url(r'^product/(?P<product_id>\d+)/new_story/', 'scrummetize_me_app.views.new_story'),
    url(r'^product/(?P<product_id>\d+)/add_story/', 'scrummetize_me_app.views.add_story'),
)

scrummetize_me/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^scrummetize_me/', include('scrummetize_me_app.urls')),
	# Uncomment the admin/doc line below to enable admin documentation:
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	
	# Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
)

scrummetize_me/scrummetize_me_app/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Tag(models.Model):
	tag = models.CharField(max_length=200)

	def __unicode__(self):
		return self.tag

class Participant(models.Model):
	participant = models.ForeignKey(User)
	
	class Meta:
		abstract = True

class Backlog(models.Model):
	name = models.CharField(max_length=200)

	def __unicode__(self):
		return self.name
		
	def ordered_stories(self):
		return self.story_set.all().order_by('-importance')
		
	def story_points(self):
		stories = self.story_set.all()
		points = 0
		for story in stories:
			points += story.estimated_points

class Product(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField(blank=True)
	creation_date = models.DateTimeField(default=datetime.datetime.now())
	wiki = models.TextField(blank=True)
	backlog = models.OneToOneField(Backlog, blank=True)

	def __unicode__(self):
		return self.name

class ProductParticipant(Participant):
	product = models.ForeignKey(Product) # Product in which the team member participates

	def __unicode__(self):
		return self.participant.username

class Sprint(models.Model):
	name = models.CharField(max_length=200)
	goal = models.CharField(max_length=400, blank=True)
	start_date = models.DateTimeField(default=datetime.datetime.now())
	end_date = models.DateTimeField()
	wiki = models.TextField(blank=True)
	
	product = models.ForeignKey(Product)
	backlog = models.OneToOneField(Backlog, blank=True)
	
	estimated_speed = models.IntegerField(blank=True)
	
	def __unicode__(self):
		return self.name

class SprintParticipant(Participant):
	participation_rate = models.FloatField(default=100, validators=[MaxValueValidator(100), MinValueValidator(1)]) # Value between 1 and 100.
	sprint = models.ForeignKey(Sprint) # Sprint in which the team member participates

	def __unicode__(self):
		return self.participant.username
	
class Story(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField(blank=True)
	estimated_points = models.IntegerField(default=0)
	importance = models.IntegerField(default=0)
	how_to_demo = models.TextField(blank=True)

	external_id = models.CharField(max_length=200, blank=True)
	requestor = models.CharField(max_length=200, blank=True)
	
	backlog = models.ForeignKey(Backlog)
	tags = models.ManyToManyField(Tag, blank=True)

	creator = models.ForeignKey(User)
	creation_date = models.DateTimeField(default=datetime.datetime.now())

	def __unicode__(self):
		return self.name

class Task(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField(blank=True)

	story = models.ForeignKey(Story)
	tags = models.ManyToManyField(Tag, blank=True)

	def __unicode__(self):
		return self.name

class Document(models.Model):
	name = models.CharField(max_length=200)
	wiki = models.TextField(blank=True)
	product = models.ForeignKey(Product)

class Note(models.Model):
	creator = models.ForeignKey(User)
	date = models.DateTimeField(default=datetime.datetime.now())
	note = models.TextField()
	
	def __unicode__(self):
		return self.note; 

	class Meta:
		abstract = True

class StoryNote(Note):
	story = models.ForeignKey(Story)

	def __unicode__(self):
		return self.note; 

class TaskNote(Note):
	task = models.ForeignKey(Task)

	def __unicode__(self):
		return self.note; 

class UploadedFile(models.Model):
	uploaded_file = models.FileField(upload_to='uploaded_files')

	class Meta:
		abstract = True

class StoryUploadedFile(UploadedFile):
	story = models.ForeignKey(Story, blank=True)

class TaskUploadedFile(UploadedFile):
	task = models.ForeignKey(Task, blank=True)

class DocumentUploadedFile(UploadedFile):
	document = models.ForeignKey(Document, blank=True)

scrummetize_me/scrummetize_me_app/views.py
# Create your views here.

from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from scrummetize_me_app.models import Product, Story
from django.http import Http404
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

#def index(request):
#	top_ten_products = Product.objects.all().order_by('-creation_date')[:10]
#	return render_to_response('scrummetize_me_app/index.html', {'top_ten_products' : top_ten_products})

#def story_detail(request, story_id):
##	try:
##		story = Story.objects.get(pk=story_id)
##	except Story.DoesNotExist:
##		raise Http404	
#	story = get_object_or_404(Story, pk=story_id)
#	return render_to_response('scrummetize_me_app/story.html', {'story':story})

def product_list(request):
	user = request.user
	products = Product.objects.filter(productparticipant__participant__id=User.objects.get(username__startswith='ruben').id)#user.id)
	return render_to_response('scrummetize_me_app/product_list.html', {'products' : products})

def new_story(request, product_id):
	return render_to_response('scrummetize_me_app/new_story.html', {'product_id':product_id}, context_instance=RequestContext(request))

def add_story(request, product_id):
	name = request.POST['name']
	description = request.POST['description']
	story_points = int(request.POST['points'])
	if not name:
		return render_to_response('scrummetize_me_app/new_story.html', {'error_message':'You must specify a name for the story'}, context_instance=RequestContext(request))
	try:
		product = get_object_or_404(Product, pk=product_id)
	except (KeyError, Product.DoesNotExist):
		raise Http404
	story = product.backlog.story_set.create(name=name, description=description, estimated_points=story_points)
	return HttpResponseRedirect(reverse('story_detail', args=(story.id)))

scrummetize_me/scrummetize_me_app/templates/scrummetize_me_app/backlog_detail.html
<h1>{{backlog.name}}</h1>
<table id="backlog_stories" class="ui-widget ui-widget-content">
	<thead>
		<tr class="ui-widget-header ">
			<th>Name</th>
			<th>Story points</th>
			<th>Importance</th>
		</tr>
	</thead>
	<tbody>
{% for story in backlog.ordered_stories %}
		<tr>
			<td>{{ story.name }}</td>
			<td>{{ story.estimated_points }}</td>
			<td>{{ story.importance }}</td>
		</tr>
{% endfor %}
	</tbody>
</table>

scrummetize_me/scrummetize_me_app/templates/scrummetize_me_app/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<title>Scrummetize Me!</title>
	<meta name="keywords" content="">
	<meta name="description" content="">
	<link href="{{ STATIC_URL }}style.css" rel="stylesheet" type="text/css" media="screen">
	</head>
<body>
	<div id="wrapper">
		<div id="logo">
			<h1>Scrummetize Me!</h1>
			<p><em> scrummetizing your world</em></p>
		</div>
		<hr>
		<!-- end #logo -->
		<div id="header">
			<div id="menu">
				<ul><li class="current_page_item"><a href="#" class="first">Home</a></li>
					<li><a href="#">About</a></li>
					<li><a href="#">Services</a></li>
					<li><a href="#">Support</a></li>
					<li>
					<li><a href="#">Contact</a></li>
				</ul>
			</div>
			<!-- end #menu -->
			<div id="search">
				<form method="get" action="">
					<fieldset>
						<input type="text" name="s" id="search-text" size="15"><input type="submit" id="search-submit" value="GO">
					</fieldset>
				</form>
			</div>
			<!-- end #search -->
		</div>
		<!-- end #header -->
	</div>
	<!-- end #header-wrapper -->
	<div id="page">
		<div id="page-bgtop">
			<div id="content">
				<div class="post">
					<h2 class="title"><a href="#">Welcome to OUR SITE</a>				</h2>
					<div class="entry">
						<p>Thank you for downloading this template. This or any other template  is  free for personal use, but you must leave our link on this page.	</p>
						<p>Here you will find help about editing our templates and empty buttons and logos for editing: </p>
		<p><a href="http://www.rickyswebtemplates.com/members/login.php">http://www.rickyswebtemplates.com/members/login.php</a>.</p>
						<p> We have created user guide with step by step instructions.</p>
						<p>If you don't know how to edit our free templates, or you don't have time we can do  that for you. For only $30 USD  we will edit logo, buttons and create few pages the way you like it. You only have to put your text  in it and your web page  is done.</p>
						<p>For more informations, contact us : webmaster@rickyswebtemplates.com</p>
						<p>For more FREE web templates and other graphics visit our site: </p>
						<p><a href="http://www.rickyswebtemplates.com">http://www.rickyswebtemplates.com</a></p>
	                </div>
				</div>
				<div class="post">
			  		<h2 class="title"><a href="#">Lorem ipsum dolor sit amet</a></h2>
			  		<p class="meta">Monday, January 26, 2010 00:00 AM Posted by <a href="#">Your name</a></p>
					<div class="entry">
				  		<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec   consectetuer. Donec ipsum. Proin imperdiet est. Phasellus <a href="#">dapibus semper urna</a>. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, ut consectetuer nisl felis ac diam. Etiam non felis. Donec ut ante. In id eros.</p>
			  		</div>
				</div>
			</div>
			<!-- end #content -->
		<div id="sidebar">
			<ul><li>
					<h2>Latest news</h2>
					<p>Thank you for downloading this template. This or any other template  is  free for personal use, but you must leave our link on this page. </p>
				</li>
				<li>
					<h2>Partners</h2>
					<ul><li><a href="#">Some link here</a></li>
						<li><a href="#">Some link here</a></li>
						<li><a href="#">Some link here</a></li>
						<li><a href="#">Some link here</a></li>
						<li><a href="#">Some link here</a></li>
					</ul></li>
			</ul></div>
		<!-- end #sidebar -->
		<div style="clear: both;"> </div>
	</div>
	</div>
	<!-- end #page -->
	<div id="footer-bgcontent">
	<div id="footer">
		<p>Copyright  2012 ScrummetizeMe.com. All rights reserved. <!--%@##--> Design provided by <a href="http://www.freewebtemplates.com/">Free Website Templates</a>.<!--##@%--></p>
<p>Find more free web templates at  <a href="http://www.rickyswebtemplates.com/" target="_blank">Free web templates</a>, <a href="http://www.webtemplates-download.com/" target="_blank">Free web layouts</a>, <a href="http://www.onlyfreewebtemplates.net/" target="_blank">Free css website templates</a></p>
	</div>
	</div>
	<!-- end #footer -->
</div>
</body></html>

scrummetize_me/scrummetize_me_app/templates/scrummetize_me_app/new_story.html
<h1>New Story for the product {{product_id}}</h1>

{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}

<form action="../add_story/" method="post">
	{% csrf_token %}
	Name: <input type="text" name="name" id="name"/><br/>
	Description: <textarea name="description" id="description"/></textarea><br/>
	Story points: <input type="text" name="points" id="points"/><br/>
	<input type="submit" value="Add"/>
</form>

scrummetize_me/scrummetize_me_app/templates/scrummetize_me_app/product_list.html
<table id="product_list" class="ui-widget ui-widget-content">
	<thead>
		<tr class="ui-widget-header ">
			<th>Name</th>
			<th>Description</th>
		</tr>
	</thead>
	<tbody>
{% for product in products %}
		<tr>
			<td>{{ product.name }}</td>
			<td>{{ product.description }}</td>
		</tr>
{% endfor %}
	</tbody>
</table>

scrummetize_me/scrummetize_me_app/templates/scrummetize_me_app/story.html
<h1>Story</h1>
{% if story %}
    <p>Name: {{ story.name }}</p>
    <p>Points: {{story.points}}</p>
    <ul>
        {% for task in story.task_set.all %}
            {{task.name}}
        {% endfor %}
    </ul>
{% else %}
    <p>No products are available.</p>
{% endif %}

scrummetize_me/scrummetize_me_app/templates/scrummetize_me_app/user-login.html
{% load i18n %}
<a href="#" id="dialog_link" class="ui-state-default ui-corner-all"><span class="ui-icon ui-icon-newwin"></span>{% 'login' %}</a>